### ISSUE TITLE
Raycasting exit_keys

### ISSUE THREAD

**Issue by FinJG** [TollyH/pygame_maze#2]
i propose an idea to show the amount of keys currently collected while in a level, as this will give you a better idea of how many keys are left to collect before the level exit opens. i think this feature would be useful as there is no good way to check how many keys are left in the Ray-casting mode. :) (i tried to add the feature myself but quickly gave up)

**Comment by TollyH** [comment]
I think this a great idea, I'll implement it soon

**Comment by TollyH** [comment]
This has now been implemented in 025c45f6a73ac5c1e6572ff279ceb58ad33ade64
