### ISSUE TITLE
"escape from monster" Loop bug

### ISSUE THREAD

**Issue by FinJG** [TollyH/pygame_maze#8]
If the player is caught by the monster on or beside the monster's spawn, the player gets stuck in a "struggle" loop as the monster instantly re-spawns and starts the struggling mechanic again, resulting in inescapable/instant death. 
maybe a short 1-2 second cool-down before the monster re-spawns would fix this :)

**Comment by TollyH** [comment]
I have fixed this in e94be3dc1bbd03ea129637a354e0aa0abeabea6b by never spawning the monster until the player is 2 units or more away from its spawn point. This also prevents them from being caught out by the initial spawn.

**Comment by FinJG** [comment]
Ooo very nice idea
