### ISSUE TITLE
Cooldown indicators for wall-placing ability

### ISSUE THREAD

**Issue by FinJG** [TollyH/pygame_maze#9]
I think adding a visual/audio indicator for the wall-placing ability would help make wall placing more strategical and would also help as a reminder to use the ability leading to it being used more often.

This could possibly be integrated with the timer and move score HUD by also being toggled by pressing "E", therefore making "E" a toggle HUD button. 

:)

**Comment by TollyH** [comment]
This has been implemented as a part of the full HUD added in bf6ff8d442a98d7f86e720459bf60ac54f5ff9de
